# Generated by Django 4.2.11 on 2025-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fin_dia',
            field=models.TimeField(default='23:59', help_text='Hora de fin del día para cálculos de tiempo restante'),
        ),
    ]
