# Generated by Django 4.2.11 on 2025-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_fin_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inicio_dia',
            field=models.TimeField(default='00:00', help_text='Hora de inicio del día para cálculos de tiempo'),
        ),
    ]
