# Generated by Django 3.2.3 on 2024-02-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('work_time', models.IntegerField()),
                ('short_break', models.IntegerField()),
                ('count', models.IntegerField()),
                ('orden_n', models.IntegerField()),
                ('color', models.CharField(default='FFFFFF', max_length=7)),
                ('objetivo', models.IntegerField(default=0)),
                ('progresion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TiposHabitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historial_habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.DurationField()),
                ('duracion_descanso', models.DurationField()),
                ('fk_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos_app.habito')),
            ],
        ),
        migrations.AddField(
            model_name='habito',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitos_app.tiposhabitos'),
        ),
    ]
