# Generated by Django 3.2.3 on 2024-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_habitos',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historial_habitos',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
