# Generated by Django 3.2.3 on 2024-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos_app', '0002_auto_20240226_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
