# Generated by Django 3.2.3 on 2024-03-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitos_app', '0003_habito_archivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_habitos',
            name='fk_habito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listHabitoHistorial', to='habitos_app.habito'),
        ),
    ]
