# Generated by Django 3.2.3 on 2024-03-06 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitos_app', '0004_alter_historial_habitos_fk_habito'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listHabitos', to=settings.AUTH_USER_MODEL),
        ),
    ]
