# Generated by Django 4.2.11 on 2025-04-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos_app', '0005_habito_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='dias_seleccionados',
            field=models.CharField(default='1,2,3,4,5,6,7', max_length=20),
        ),
    ]
