# Generated by Django 4.2.11 on 2025-05-21 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitos_app', '0006_habito_dias_seleccionados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(default='#CCCCCC', max_length=7)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='habito',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='habitos', to='habitos_app.tag'),
        ),
        migrations.CreateModel(
            name='TagStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tiempo_total', models.DurationField(default=datetime.timedelta(0))),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='habitos_app.tag')),
            ],
            options={
                'unique_together': {('tag', 'fecha')},
            },
        ),
    ]
