# Generated by Django 4.2.11 on 2026-07-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos_app', '0010_habito_favorites_and_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='hora_inicio',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='hora_limite',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
